site_name: Note Log
site_description: '记录笔记'
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.path         
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
        permalink: True
        separator: "-"
        toc_depth: 5
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower

plugins:
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      archive: true
      categories: true
      pagination: true
      pagination_per_page: 10
      post_url_date_format: ""
  - tags
  - awesome-pages
  - search:
      separator: '[\s\u200b\-]'